{ "height":20,
 "layers":[
        {
         "compression":"zlib",
         "data":"eJxjYBgYYDWKR\/EoHsWjeBSP4lE8TDEAQbiBJQ==",
         "encoding":"base64",
         "height":20,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYBhYkDJq74i1N4UMTC17SQGj9o7aO2ov\/e2lRjlAqr3UBKP2jtoLAEGGFeE=",
         "encoding":"base64",
         "height":20,
         "name":"road",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYBg4oA2ldUbtHTB7dSjAlNpLDqCWvdokYGrbSwwYtXfU3sFkL678T0t7KVVDjr3ElgfUtJeaYNTewWUvAItsEwk=",
         "encoding":"base64",
         "height":20,
         "name":"Tile Layer 3",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "properties":
    {

    },
 "renderorder":"right-down",
 "tileheight":35,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tileset.gif",
         "imageheight":512,
         "imagewidth":512,
         "margin":1,
         "name":"tileset",
         "properties":
            {

            },
         "spacing":1,
         "tilecount":196,
         "tileheight":35,
         "tilewidth":35
        }],
 "tilewidth":35,
 "version":1,
 "width":30
}